name: smart_delivery_robot
description: A Smart Delivery Robot App using basic Flutter widgets (Lab 5)

publish_to: 'none' # Remove this line if publishing

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Default icons (optional but recommended)
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true